name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true

      # Check this about more info: https://github.com/marketplace/actions/cmake-action
      - name: Set Up CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: false

      - name: Configure
        shell: cmd
        run: |
          rmdir /s /q build > nul 2> nul
          cmake -B build -G "Visual Studio 17 2022" -A Win32

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout2-re
          path:  build/RelWithDebInfo/fallout2-re.exe
